version: "0.2"

phases:
  install:
    commands:
      - "mkdir -p /tmp/opt/npm/lib"
      - "npm ci --workspace=kaito-tokyo-aws-kaito-tokyo-management"

  build:
    commands:
      - "cd KaitoTokyoManagement"
      - "./update.sh"
