---
name: "deploy-infrastructure"

on:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: "bash"

jobs:
  DeployInfrastructure:
    runs-on:
      - "codebuild-CDKRunner-${{ github.run_id }}-${{ github.run_attempt }}"
      - "image:arm-lambda-nodejs20"
      - "instance-size:1GB"

    concurrency:
      group: "${{ github.workflow }}-main"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Fix npm"
        run: "mkdir -p /tmp/opt/npm/lib"

