---
name: "prettier"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

defaults:
  run:
    shell: "bash"

jobs:
  Prettier:
    runs-on:
      - "codebuild-ManageServiceCodeBuildProjects-${{ github.run_id }}-${{ github.run_attempt }}"
      - "image:arm-lambda-nodejs20"
      - "instance-size:1GB"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
